jQuery(function(){initCustomForms();initLoadMore();initBgParallax();initMasonry();initOpenClose();initSameHeight();});function initCustomForms(){jcf.setOptions('Select',{wrapNative:false,wrapNativeOnMobile:false});jcf.replaceAll('');}
function initOpenClose(){jQuery('div.open-close').openClose({activeClass:'active',opener:'.opener',slider:'.slide',animSpeed:400,effect:'slide'});}
function initLoadMore(){jQuery('.load-more-holder').loadMore({linkSelector:'.load-more',additionBottomOffset:80});}
function initBgParallax(){jQuery('.bg-parallax-holder').parallaxBlock({image:'> img',parallaxOffset:150});}
function initMasonry(){jQuery(window).on('load masonry/refresh',function(){jQuery('.js-masonry').masonry({"columnWidth":1,"itemSelector":".grid-item","isResizeBound":true,"percentPosition":true,"originLeft":true});});}
function initSameHeight(){jQuery('.columns-holder').sameHeight({elements:'.column',flexible:true,multiLine:true,biggestHeight:true});jQuery('.slick-gallery-moods').sameHeight({elements:'.slide-item',flexible:true,multiLine:true,biggestHeight:true});}
function initRefresh(){if($(".player").size()){var videoUrl;jQuery(".player").tubeplayer({width:'100%',height:'100%',allowFullScreen:"true",initialVideo:videoUrl,preferredQuality:"hd1080"});jQuery(document).on('click','.play-box',function(event){event.preventDefault();videoUrl=jQuery(this).attr('href');jQuery(this).closest('.video-post').addClass('playback').find('.player').tubeplayer('play',videoUrl);});}
if('masonry'in $.fn){jQuery('.js-masonry').masonry({"columnWidth":1,"itemSelector":".grid-item","isResizeBound":true,"percentPosition":true});}};(function($){$.fn.sameHeight=function(opt){var options=$.extend({skipClass:'same-height-ignore',leftEdgeClass:'same-height-left',rightEdgeClass:'same-height-right',elements:'>*',flexible:false,multiLine:false,useMinHeight:false,biggestHeight:false},opt);return this.each(function(){var holder=$(this),postResizeTimer,ignoreResize;var elements=holder.find(options.elements).not('.'+options.skipClass);if(!elements.length)return;function doResize(){elements.css(options.useMinHeight&&supportMinHeight?'minHeight':'height','');if(options.multiLine){resizeElementsByRows(elements,options);}else{resizeElements(elements,holder,options);}}
doResize();var delayedResizeHandler=function(){if(!ignoreResize){ignoreResize=true;doResize();clearTimeout(postResizeTimer);postResizeTimer=setTimeout(function(){doResize();setTimeout(function(){ignoreResize=false;},10);},100);}};if(options.flexible){$(window).bind('resize orientationchange fontresize',delayedResizeHandler);}
$(window).bind('load',delayedResizeHandler);});};var supportMinHeight=typeof document.documentElement.style.maxHeight!=='undefined';function resizeElementsByRows(boxes,options){var currentRow=$(),maxHeight,maxCalcHeight=0,firstOffset=boxes.eq(0).offset().top;boxes.each(function(ind){var curItem=$(this);if(curItem.offset().top===firstOffset){currentRow=currentRow.add(this);}else{maxHeight=getMaxHeight(currentRow);maxCalcHeight=Math.max(maxCalcHeight,resizeElements(currentRow,maxHeight,options));currentRow=curItem;firstOffset=curItem.offset().top;}});if(currentRow.length){maxHeight=getMaxHeight(currentRow);maxCalcHeight=Math.max(maxCalcHeight,resizeElements(currentRow,maxHeight,options));}
if(options.biggestHeight){boxes.css(options.useMinHeight&&supportMinHeight?'minHeight':'height',maxCalcHeight);}}
function getMaxHeight(boxes){var maxHeight=0;boxes.each(function(){maxHeight=Math.max(maxHeight,$(this).outerHeight());});return maxHeight;}
function resizeElements(boxes,parent,options){var calcHeight;var parentHeight=typeof parent==='number'?parent:parent.height();boxes.removeClass(options.leftEdgeClass).removeClass(options.rightEdgeClass).each(function(i){var element=$(this);var depthDiffHeight=0;var isBorderBox=element.css('boxSizing')==='border-box'||element.css('-moz-box-sizing')==='border-box'||element.css('-webkit-box-sizing')==='border-box';if(typeof parent!=='number'){element.parents().each(function(){var tmpParent=$(this);if(parent.is(this)){return false;}else{depthDiffHeight+=tmpParent.outerHeight()-tmpParent.height();}});}
calcHeight=parentHeight-depthDiffHeight;calcHeight-=isBorderBox?0:element.outerHeight()-element.height();if(calcHeight>0){element.css(options.useMinHeight&&supportMinHeight?'minHeight':'height',calcHeight);}});boxes.filter(':first').addClass(options.leftEdgeClass);boxes.filter(':last').addClass(options.rightEdgeClass);return calcHeight;}}(jQuery));;(function($){function OpenClose(options){this.options=$.extend({addClassBeforeAnimation:true,hideOnClickOutside:false,activeClass:'active',opener:'.opener',slider:'.slide',animSpeed:400,effect:'fade',event:'click'},options);this.init();}
OpenClose.prototype={init:function(){if(this.options.holder){this.findElements();this.attachEvents();this.makeCallback('onInit',this);}},findElements:function(){this.holder=$(this.options.holder);this.opener=this.holder.find(this.options.opener);this.slider=this.holder.find(this.options.slider);},attachEvents:function(){var self=this;this.eventHandler=function(e){e.preventDefault();if(self.slider.hasClass(slideHiddenClass)){self.showSlide();}else{self.hideSlide();}};self.opener.bind(self.options.event,this.eventHandler);if(self.options.event==='over'){self.opener.bind('mouseenter',function(){if(!self.holder.hasClass(self.options.activeClass)){self.showSlide();}});self.holder.bind('mouseleave',function(){self.hideSlide();});}
self.outsideClickHandler=function(e){if(self.options.hideOnClickOutside){var target=$(e.target);if(!target.is(self.holder)&&!target.closest(self.holder).length){self.hideSlide();}}};if(this.holder.hasClass(this.options.activeClass)){$(document).bind('click touchstart',self.outsideClickHandler);}else{this.slider.addClass(slideHiddenClass);}},showSlide:function(){var self=this;if(self.options.addClassBeforeAnimation){self.holder.addClass(self.options.activeClass);}
self.slider.removeClass(slideHiddenClass);$(document).bind('click touchstart',self.outsideClickHandler);self.makeCallback('animStart',true);toggleEffects[self.options.effect].show({box:self.slider,speed:self.options.animSpeed,complete:function(){if(!self.options.addClassBeforeAnimation){self.holder.addClass(self.options.activeClass);}
self.makeCallback('animEnd',true);}});},hideSlide:function(){var self=this;if(self.options.addClassBeforeAnimation){self.holder.removeClass(self.options.activeClass);}
$(document).unbind('click touchstart',self.outsideClickHandler);self.makeCallback('animStart',false);toggleEffects[self.options.effect].hide({box:self.slider,speed:self.options.animSpeed,complete:function(){if(!self.options.addClassBeforeAnimation){self.holder.removeClass(self.options.activeClass);}
self.slider.addClass(slideHiddenClass);self.makeCallback('animEnd',false);}});},destroy:function(){this.slider.removeClass(slideHiddenClass).css({display:''});this.opener.unbind(this.options.event,this.eventHandler);this.holder.removeClass(this.options.activeClass).removeData('OpenClose');$(document).unbind('click touchstart',this.outsideClickHandler);},makeCallback:function(name){if(typeof this.options[name]==='function'){var args=Array.prototype.slice.call(arguments);args.shift();this.options[name].apply(this,args);}}};var slideHiddenClass='js-slide-hidden';(function(){var tabStyleSheet=$('<style type="text/css">')[0];var tabStyleRule='.'+slideHiddenClass;tabStyleRule+='{position:absolute !important;left:-9999px !important;top:-9999px !important;display:block !important}';if(tabStyleSheet.styleSheet){tabStyleSheet.styleSheet.cssText=tabStyleRule;}else{tabStyleSheet.appendChild(document.createTextNode(tabStyleRule));}
$('head').append(tabStyleSheet);}());var toggleEffects={slide:{show:function(o){o.box.stop(true).hide().slideDown(o.speed,o.complete);},hide:function(o){o.box.stop(true).slideUp(o.speed,o.complete);}},fade:{show:function(o){o.box.stop(true).hide().fadeIn(o.speed,o.complete);},hide:function(o){o.box.stop(true).fadeOut(o.speed,o.complete);}},none:{show:function(o){o.box.hide().show(0,o.complete);},hide:function(o){o.box.hide(0,o.complete);}}};$.fn.openClose=function(opt){return this.each(function(){jQuery(this).data('OpenClose',new OpenClose($.extend(opt,{holder:this})));});};}(jQuery));;(function($,$win){'use strict';var ScrollLoader={attachEvents:function(){var self=this;$win.on('load.ScrollLoader resize.ScrollLoader orientationchange.ScrollLoader',function(){self.onResizeHandler();});$win.on('scroll.ScrollLoader',function(){self.onScrollHandler();});this.$holder.on('ContentLoader/loaded.ScrollLoader',function(){self.onResizeHandler();});this.winProps={};this.holderProps={};this.onResizeHandler();},onResizeHandler:function(){this.winProps.height=$win.height();this.holderProps.height=this.$holder.outerHeight();this.holderProps.offset=this.$holder.offset().top;this.onScrollHandler();},onScrollHandler:function(){this.winProps.scroll=$win.scrollTop();if(this.winProps.scroll+this.winProps.height+Math.min(1,this.options.additionBottomOffset)>this.holderProps.height+this.holderProps.offset){this.loadInclude();}},destroySubEvents:function(){$win.off('.ScrollLoader');this.$holder.off('.ScrollLoader');}};var ClickLoader={attachEvents:function(){var self=this;this.$holder.on('click.ClickLoader',this.options.linkSelector,function(e){self.onClickHandler(e);});},onClickHandler:function(e){e.preventDefault();this.loadInclude();},destroySubEvents:function(){this.$holder.off('.ClickLoader');}};var ContentLoader=function($holder,options){this.$holder=$holder;this.options=options;this.init();};var ContentLoaderProto={init:function(){this.$link=this.$holder.find(this.options.linkSelector);this.$newContentTarget=this.options.newContentTarget?this.$holder.find(this.options.newContentTarget):this.$holder;if(!this.$link.length){this.removeInstance();return;}
this.attachEvents();},loadInclude:function(){if(this.isBusy){return;}
var self=this;this.toggleBusyMode(true);$.get(self.$link.attr('href'),function(source){self.successHandler(source);});},successHandler:function(include){var $tmpDiv=jQuery('<div>').html(include);var $nextIncludeLink=$tmpDiv.find(this.options.linkSelector);if($nextIncludeLink.length){this.refreshLink($nextIncludeLink);}else{this.destroy();}
this.appendItems($tmpDiv.children());},appendItems:function($newItems){var self=this;this.$newContentTarget.append($newItems.addClass(this.options.preAppendClass));setTimeout(function(){$newItems.removeClass(self.options.preAppendClass);self.$holder.trigger('ContentLoader/loaded');self.toggleBusyMode(false);initRefresh();},100);if(window.picturefill){window.picturefill();}},refreshLink:function($nextIncludeLink){this.$link.attr('href',$nextIncludeLink.attr('href'));$nextIncludeLink.remove();},toggleBusyMode:function(state){this.$holder.toggleClass(this.options.busyClass,state);this.isBusy=state;},removeInstance:function(){this.$holder.removeData('ContentLoader');},destroy:function(){this.removeInstance();this.destroySubEvents();this.$link.remove();}};$.fn.loadMore=function(options){options=$.extend({scroll:false,linkSelector:'.load-more',newContentTarget:null,busyClass:'is-busy',additionBottomOffset:50,preAppendClass:'new-item'},options);return this.each(function(){var $holder=$(this);ContentLoader.prototype=$.extend(options.scroll?ScrollLoader:ClickLoader,ContentLoaderProto);$holder.data('ContentLoader',new ContentLoader($holder,options));});};}(jQuery,jQuery(window)));;(function($){'use strict';var isTouchDevice=/MSIE 10.*Touch/.test(navigator.userAgent)||('ontouchstart'in window)||window.DocumentTouch&&document instanceof DocumentTouch;var ParallaxController=(function(){var $win=$(window);var items=[];var winProps={width:0,height:0,scrollTop:0};return{init:function(){$win.on('load resize orientationchange',this.resizeHandler.bind(this));$win.on('scroll',this.scrollHandler.bind(this));this.resizeHandler();},resizeHandler:function(){winProps.width=$win.width();winProps.height=$win.height();$.each(items,this.calculateSize.bind(this));},scrollHandler:function(){winProps.scrollTop=$win.scrollTop();$.each(items,this.calculateScroll.bind(this));},calculateSize:function(i){var item=items[i];var bgWidth;var bgHeight;item.height=item.$el.outerHeight();item.width=item.$el.outerWidth();item.topOffset=item.$el.offset().top;item.bgHeight=winProps.height+item.options.parallaxOffset;item.itemRatio=winProps.width/(winProps.height+item.options.parallaxOffset);if(item.imageRatio<=item.itemRatio){bgWidth=winProps.width;bgHeight=bgWidth/item.imageRatio;bgWidth+='px ';bgHeight+='px ';}else{bgWidth='auto ';bgHeight=winProps.height+item.options.parallaxOffset;bgHeight+='px ';}
item.$el.css({backgroundSize:bgWidth+bgHeight});this.calculateScroll(i);},calculateScroll:function(i){var item=items[i];var curPos;var offsetPercentage=Math.max(0,Math.min((winProps.scrollTop+winProps.height-item.topOffset)/(winProps.height+item.height),1)).toFixed(4);if(item.imageRatio<=item.itemRatio){curPos='50% '+((-parseFloat(offsetPercentage)*item.options.parallaxOffset)-(item.bgHeight-winProps.height)/2)+'px';}else{curPos='50% '+(-parseFloat(offsetPercentage)*item.options.parallaxOffset)+'px';}
item.$el.css({backgroundPosition:curPos});},add:function(el,options){var $el=$(el);var $image=$el.find(options.image);var imageRatio=$image.attr('width')/$image.attr('height')||$image.width()/$image.height();$el.css({backgroundImage:'url('+$image.attr('src')+')'});if(isTouchDevice){$el.addClass(options.fallbackClass);return;}
$image.remove();options.parallaxOffset=Math.abs(options.parallaxOffset);var newIndex=items.push({$el:$(el),options:options,imageRatio:imageRatio});this.calculateSize(newIndex-1);}};}());ParallaxController.init();$.fn.parallaxBlock=function(options){options=$.extend({parallaxOffset:100,fallbackClass:'fallback-class',image:'img'},options);return this.each(function(){if(this.added){return;}
this.added=true;ParallaxController.add(this,options);});};}(jQuery));!function(a){function b(){}
function c(a){function c(b){b.prototype.option||(b.prototype.option=function(b){a.isPlainObject(b)&&(this.options=a.extend(!0,this.options,b))})}
function e(b,c){a.fn[b]=function(e){if("string"==typeof e){for(var g=d.call(arguments,1),h=0,i=this.length;i>h;h++){var j=this[h],k=a.data(j,b);if(k)
if(a.isFunction(k[e])&&"_"!==e.charAt(0)){var l=k[e].apply(k,g);if(void 0!==l)return l}else f("no such method '"+e+"' for "+b+" instance");else f("cannot call methods on "+b+" prior to initialization; attempted to call '"+e+"'")}
return this}
return this.each(function(){var d=a.data(this,b);d?(d.option(e),d._init()):(d=new c(this,e),a.data(this,b,d))})}}
if(a){var f="undefined"==typeof console?b:function(a){console.error(a)};return a.bridget=function(a,b){c(b),e(a,b)},a.bridget}}
var d=Array.prototype.slice;"function"==typeof define&&define.amd?define("jquery-bridget/jquery.bridget",["jquery"],c):c("object"==typeof exports?require("jquery"):a.jQuery)}(window),function(a){function b(b){var c=a.event;return c.target=c.target||c.srcElement||b,c}
var c=document.documentElement,d=function(){};c.addEventListener?d=function(a,b,c){a.addEventListener(b,c,!1)}:c.attachEvent&&(d=function(a,c,d){a[c+d]=d.handleEvent?function(){var c=b(a);d.handleEvent.call(d,c)}:function(){var c=b(a);d.call(a,c)},a.attachEvent("on"+c,a[c+d])});var e=function(){};c.removeEventListener?e=function(a,b,c){a.removeEventListener(b,c,!1)}:c.detachEvent&&(e=function(a,b,c){a.detachEvent("on"+b,a[b+c]);try{delete a[b+c]}catch(d){a[b+c]=void 0}});var f={bind:d,unbind:e};"function"==typeof define&&define.amd?define("eventie/eventie",f):"object"==typeof exports?module.exports=f:a.eventie=f}(window),function(){function a(){}
function b(a,b){for(var c=a.length;c--;)
if(a[c].listener===b)return c;return-1}
function c(a){return function(){return this[a].apply(this,arguments)}}
var d=a.prototype,e=this,f=e.EventEmitter;d.getListeners=function(a){var b,c,d=this._getEvents();if(a instanceof RegExp){b={};for(c in d)d.hasOwnProperty(c)&&a.test(c)&&(b[c]=d[c])}else b=d[a]||(d[a]=[]);return b},d.flattenListeners=function(a){var b,c=[];for(b=0;b<a.length;b+=1)c.push(a[b].listener);return c},d.getListenersAsObject=function(a){var b,c=this.getListeners(a);return c instanceof Array&&(b={},b[a]=c),b||c},d.addListener=function(a,c){var d,e=this.getListenersAsObject(a),f="object"==typeof c;for(d in e)e.hasOwnProperty(d)&&-1===b(e[d],c)&&e[d].push(f?c:{listener:c,once:!1});return this},d.on=c("addListener"),d.addOnceListener=function(a,b){return this.addListener(a,{listener:b,once:!0})},d.once=c("addOnceListener"),d.defineEvent=function(a){return this.getListeners(a),this},d.defineEvents=function(a){for(var b=0;b<a.length;b+=1)this.defineEvent(a[b]);return this},d.removeListener=function(a,c){var d,e,f=this.getListenersAsObject(a);for(e in f)f.hasOwnProperty(e)&&(d=b(f[e],c),-1!==d&&f[e].splice(d,1));return this},d.off=c("removeListener"),d.addListeners=function(a,b){return this.manipulateListeners(!1,a,b)},d.removeListeners=function(a,b){return this.manipulateListeners(!0,a,b)},d.manipulateListeners=function(a,b,c){var d,e,f=a?this.removeListener:this.addListener,g=a?this.removeListeners:this.addListeners;if("object"!=typeof b||b instanceof RegExp)
for(d=c.length;d--;)f.call(this,b,c[d]);else
for(d in b)b.hasOwnProperty(d)&&(e=b[d])&&("function"==typeof e?f.call(this,d,e):g.call(this,d,e));return this},d.removeEvent=function(a){var b,c=typeof a,d=this._getEvents();if("string"===c)delete d[a];else if(a instanceof RegExp)
for(b in d)d.hasOwnProperty(b)&&a.test(b)&&delete d[b];else delete this._events;return this},d.removeAllListeners=c("removeEvent"),d.emitEvent=function(a,b){var c,d,e,f,g=this.getListenersAsObject(a);for(e in g)
if(g.hasOwnProperty(e))
for(d=g[e].length;d--;)c=g[e][d],c.once===!0&&this.removeListener(a,c.listener),f=c.listener.apply(this,b||[]),f===this._getOnceReturnValue()&&this.removeListener(a,c.listener);return this},d.trigger=c("emitEvent"),d.emit=function(a){var b=Array.prototype.slice.call(arguments,1);return this.emitEvent(a,b)},d.setOnceReturnValue=function(a){return this._onceReturnValue=a,this},d._getOnceReturnValue=function(){return this.hasOwnProperty("_onceReturnValue")?this._onceReturnValue:!0},d._getEvents=function(){return this._events||(this._events={})},a.noConflict=function(){return e.EventEmitter=f,a},"function"==typeof define&&define.amd?define("eventEmitter/EventEmitter",[],function(){return a}):"object"==typeof module&&module.exports?module.exports=a:e.EventEmitter=a}.call(this),function(a){function b(a){if(a){if("string"==typeof d[a])return a;a=a.charAt(0).toUpperCase()+a.slice(1);for(var b,e=0,f=c.length;f>e;e++)
if(b=c[e]+a,"string"==typeof d[b])return b}}
var c="Webkit Moz ms Ms O".split(" "),d=document.documentElement.style;"function"==typeof define&&define.amd?define("get-style-property/get-style-property",[],function(){return b}):"object"==typeof exports?module.exports=b:a.getStyleProperty=b}(window),function(a){function b(a){var b=parseFloat(a),c=-1===a.indexOf("%")&&!isNaN(b);return c&&b}
function c(){}
function d(){for(var a={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0},b=0,c=g.length;c>b;b++){var d=g[b];a[d]=0}
return a}
function e(c){function e(){if(!m){m=!0;var d=a.getComputedStyle;if(j=function(){var a=d?function(a){return d(a,null)}:function(a){return a.currentStyle};return function(b){var c=a(b);return c||f("Style returned "+c+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1"),c}}(),k=c("boxSizing")){var e=document.createElement("div");e.style.width="200px",e.style.padding="1px 2px 3px 4px",e.style.borderStyle="solid",e.style.borderWidth="1px 2px 3px 4px",e.style[k]="border-box";var g=document.body||document.documentElement;g.appendChild(e);var h=j(e);l=200===b(h.width),g.removeChild(e)}}}
function h(a){if(e(),"string"==typeof a&&(a=document.querySelector(a)),a&&"object"==typeof a&&a.nodeType){var c=j(a);if("none"===c.display)return d();var f={};f.width=a.offsetWidth,f.height=a.offsetHeight;for(var h=f.isBorderBox=!(!k||!c[k]||"border-box"!==c[k]),m=0,n=g.length;n>m;m++){var o=g[m],p=c[o];p=i(a,p);var q=parseFloat(p);f[o]=isNaN(q)?0:q}
var r=f.paddingLeft+f.paddingRight,s=f.paddingTop+f.paddingBottom,t=f.marginLeft+f.marginRight,u=f.marginTop+f.marginBottom,v=f.borderLeftWidth+f.borderRightWidth,w=f.borderTopWidth+f.borderBottomWidth,x=h&&l,y=b(c.width);y!==!1&&(f.width=y+(x?0:r+v));var z=b(c.height);return z!==!1&&(f.height=z+(x?0:s+w)),f.innerWidth=f.width-(r+v),f.innerHeight=f.height-(s+w),f.outerWidth=f.width+t,f.outerHeight=f.height+u,f}}
function i(b,c){if(a.getComputedStyle||-1===c.indexOf("%"))return c;var d=b.style,e=d.left,f=b.runtimeStyle,g=f&&f.left;return g&&(f.left=b.currentStyle.left),d.left=c,c=d.pixelLeft,d.left=e,g&&(f.left=g),c}
var j,k,l,m=!1;return h}
var f="undefined"==typeof console?c:function(a){console.error(a)},g=["paddingLeft","paddingRight","paddingTop","paddingBottom","marginLeft","marginRight","marginTop","marginBottom","borderLeftWidth","borderRightWidth","borderTopWidth","borderBottomWidth"];"function"==typeof define&&define.amd?define("get-size/get-size",["get-style-property/get-style-property"],e):"object"==typeof exports?module.exports=e(require("desandro-get-style-property")):a.getSize=e(a.getStyleProperty)}(window),function(a){function b(a){"function"==typeof a&&(b.isReady?a():g.push(a))}
function c(a){var c="readystatechange"===a.type&&"complete"!==f.readyState;b.isReady||c||d()}
function d(){b.isReady=!0;for(var a=0,c=g.length;c>a;a++){var d=g[a];d()}}
function e(e){return"complete"===f.readyState?d():(e.bind(f,"DOMContentLoaded",c),e.bind(f,"readystatechange",c),e.bind(a,"load",c)),b}
var f=a.document,g=[];b.isReady=!1,"function"==typeof define&&define.amd?define("doc-ready/doc-ready",["eventie/eventie"],e):"object"==typeof exports?module.exports=e(require("eventie")):a.docReady=e(a.eventie)}(window),function(a){function b(a,b){return a[g](b)}
function c(a){if(!a.parentNode){var b=document.createDocumentFragment();b.appendChild(a)}}
function d(a,b){c(a);for(var d=a.parentNode.querySelectorAll(b),e=0,f=d.length;f>e;e++)
if(d[e]===a)return!0;return!1}
function e(a,d){return c(a),b(a,d)}
var f,g=function(){if(a.matches)return"matches";if(a.matchesSelector)return"matchesSelector";for(var b=["webkit","moz","ms","o"],c=0,d=b.length;d>c;c++){var e=b[c],f=e+"MatchesSelector";if(a[f])return f}}();if(g){var h=document.createElement("div"),i=b(h,"div");f=i?b:e}else f=d;"function"==typeof define&&define.amd?define("matches-selector/matches-selector",[],function(){return f}):"object"==typeof exports?module.exports=f:window.matchesSelector=f}(Element.prototype),function(a,b){"function"==typeof define&&define.amd?define("fizzy-ui-utils/utils",["doc-ready/doc-ready","matches-selector/matches-selector"],function(c,d){return b(a,c,d)}):"object"==typeof exports?module.exports=b(a,require("doc-ready"),require("desandro-matches-selector")):a.fizzyUIUtils=b(a,a.docReady,a.matchesSelector)}(window,function(a,b,c){var d={};d.extend=function(a,b){for(var c in b)a[c]=b[c];return a},d.modulo=function(a,b){return(a%b+b)%b};var e=Object.prototype.toString;d.isArray=function(a){return"[object Array]"==e.call(a)},d.makeArray=function(a){var b=[];if(d.isArray(a))b=a;else if(a&&"number"==typeof a.length)
for(var c=0,e=a.length;e>c;c++)b.push(a[c]);else b.push(a);return b},d.indexOf=Array.prototype.indexOf?function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,d=a.length;d>c;c++)
if(a[c]===b)return c;return-1},d.removeFrom=function(a,b){var c=d.indexOf(a,b);-1!=c&&a.splice(c,1)},d.isElement="function"==typeof HTMLElement||"object"==typeof HTMLElement?function(a){return a instanceof HTMLElement}:function(a){return a&&"object"==typeof a&&1==a.nodeType&&"string"==typeof a.nodeName},d.setText=function(){function a(a,c){b=b||(void 0!==document.documentElement.textContent?"textContent":"innerText"),a[b]=c}
var b;return a}(),d.getParent=function(a,b){for(;a!=document.body;)
if(a=a.parentNode,c(a,b))return a},d.getQueryElement=function(a){return"string"==typeof a?document.querySelector(a):a},d.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},d.filterFindElements=function(a,b){a=d.makeArray(a);for(var e=[],f=0,g=a.length;g>f;f++){var h=a[f];if(d.isElement(h))
if(b){c(h,b)&&e.push(h);for(var i=h.querySelectorAll(b),j=0,k=i.length;k>j;j++)e.push(i[j])}else e.push(h)}
return e},d.debounceMethod=function(a,b,c){var d=a.prototype[b],e=b+"Timeout";a.prototype[b]=function(){var a=this[e];a&&clearTimeout(a);var b=arguments,f=this;this[e]=setTimeout(function(){d.apply(f,b),delete f[e]},c||100)}},d.toDashed=function(a){return a.replace(/(.)([A-Z])/g,function(a,b,c){return b+"-"+c}).toLowerCase()};var f=a.console;return d.htmlInit=function(c,e){b(function(){for(var b=d.toDashed(e),g=document.querySelectorAll(".js-"+b),h="data-"+b+"-options",i=0,j=g.length;j>i;i++){var k,l=g[i],m=l.getAttribute(h);try{k=m&&JSON.parse(m)}catch(n){f&&f.error("Error parsing "+h+" on "+l.nodeName.toLowerCase()+(l.id?"#"+l.id:"")+": "+n);continue}
var o=new c(l,k),p=a.jQuery;p&&p.data(l,e,o)}})},d}),function(a,b){"function"==typeof define&&define.amd?define("outlayer/item",["eventEmitter/EventEmitter","get-size/get-size","get-style-property/get-style-property","fizzy-ui-utils/utils"],function(c,d,e,f){return b(a,c,d,e,f)}):"object"==typeof exports?module.exports=b(a,require("wolfy87-eventemitter"),require("get-size"),require("desandro-get-style-property"),require("fizzy-ui-utils")):(a.Outlayer={},a.Outlayer.Item=b(a,a.EventEmitter,a.getSize,a.getStyleProperty,a.fizzyUIUtils))}(window,function(a,b,c,d,e){function f(a){for(var b in a)return!1;return b=null,!0}
function g(a,b){a&&(this.element=a,this.layout=b,this.position={x:0,y:0},this._create())}
function h(a){return a.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()})}
var i=a.getComputedStyle,j=i?function(a){return i(a,null)}:function(a){return a.currentStyle},k=d("transition"),l=d("transform"),m=k&&l,n=!!d("perspective"),o={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"otransitionend",transition:"transitionend"}[k],p=["transform","transition","transitionDuration","transitionProperty"],q=function(){for(var a={},b=0,c=p.length;c>b;b++){var e=p[b],f=d(e);f&&f!==e&&(a[e]=f)}
return a}();e.extend(g.prototype,b.prototype),g.prototype._create=function(){this._transn={ingProperties:{},clean:{},onEnd:{}},this.css({position:"absolute"})},g.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},g.prototype.getSize=function(){this.size=c(this.element)},g.prototype.css=function(a){var b=this.element.style;for(var c in a){var d=q[c]||c;b[d]=a[c]}},g.prototype.getPosition=function(){var a=j(this.element),b=this.layout.options,c=b.isOriginLeft,d=b.isOriginTop,e=a[c?"left":"right"],f=a[d?"top":"bottom"],g=this.layout.size,h=-1!=e.indexOf("%")?parseFloat(e)/100*g.width:parseInt(e,10),i=-1!=f.indexOf("%")?parseFloat(f)/100*g.height:parseInt(f,10);h=isNaN(h)?0:h,i=isNaN(i)?0:i,h-=c?g.paddingLeft:g.paddingRight,i-=d?g.paddingTop:g.paddingBottom,this.position.x=h,this.position.y=i},g.prototype.layoutPosition=function(){var a=this.layout.size,b=this.layout.options,c={},d=b.isOriginLeft?"paddingLeft":"paddingRight",e=b.isOriginLeft?"left":"right",f=b.isOriginLeft?"right":"left",g=this.position.x+a[d];c[e]=this.getXValue(g),c[f]="";var h=b.isOriginTop?"paddingTop":"paddingBottom",i=b.isOriginTop?"top":"bottom",j=b.isOriginTop?"bottom":"top",k=this.position.y+a[h];c[i]=this.getYValue(k),c[j]="",this.css(c),this.emitEvent("layout",[this])},g.prototype.getXValue=function(a){var b=this.layout.options;return b.percentPosition&&!b.isHorizontal?a/this.layout.size.width*100+"%":a+"px"},g.prototype.getYValue=function(a){var b=this.layout.options;return b.percentPosition&&b.isHorizontal?a/this.layout.size.height*100+"%":a+"px"},g.prototype._transitionTo=function(a,b){this.getPosition();var c=this.position.x,d=this.position.y,e=parseInt(a,10),f=parseInt(b,10),g=e===this.position.x&&f===this.position.y;if(this.setPosition(a,b),g&&!this.isTransitioning)return void this.layoutPosition();var h=a-c,i=b-d,j={};j.transform=this.getTranslate(h,i),this.transition({to:j,onTransitionEnd:{transform:this.layoutPosition},isCleaning:!0})},g.prototype.getTranslate=function(a,b){var c=this.layout.options;return a=c.isOriginLeft?a:-a,b=c.isOriginTop?b:-b,n?"translate3d("+a+"px, "+b+"px, 0)":"translate("+a+"px, "+b+"px)"},g.prototype.goTo=function(a,b){this.setPosition(a,b),this.layoutPosition()},g.prototype.moveTo=m?g.prototype._transitionTo:g.prototype.goTo,g.prototype.setPosition=function(a,b){this.position.x=parseInt(a,10),this.position.y=parseInt(b,10)},g.prototype._nonTransition=function(a){this.css(a.to),a.isCleaning&&this._removeStyles(a.to);for(var b in a.onTransitionEnd)a.onTransitionEnd[b].call(this)},g.prototype._transition=function(a){if(!parseFloat(this.layout.options.transitionDuration))return void this._nonTransition(a);var b=this._transn;for(var c in a.onTransitionEnd)b.onEnd[c]=a.onTransitionEnd[c];for(c in a.to)b.ingProperties[c]=!0,a.isCleaning&&(b.clean[c]=!0);if(a.from){this.css(a.from);var d=this.element.offsetHeight;d=null}
this.enableTransition(a.to),this.css(a.to),this.isTransitioning=!0};var r="opacity,"+h(q.transform||"transform");g.prototype.enableTransition=function(){this.isTransitioning||(this.css({transitionProperty:r,transitionDuration:this.layout.options.transitionDuration}),this.element.addEventListener(o,this,!1))},g.prototype.transition=g.prototype[k?"_transition":"_nonTransition"],g.prototype.onwebkitTransitionEnd=function(a){this.ontransitionend(a)},g.prototype.onotransitionend=function(a){this.ontransitionend(a)};var s={"-webkit-transform":"transform","-moz-transform":"transform","-o-transform":"transform"};g.prototype.ontransitionend=function(a){if(a.target===this.element){var b=this._transn,c=s[a.propertyName]||a.propertyName;if(delete b.ingProperties[c],f(b.ingProperties)&&this.disableTransition(),c in b.clean&&(this.element.style[a.propertyName]="",delete b.clean[c]),c in b.onEnd){var d=b.onEnd[c];d.call(this),delete b.onEnd[c]}
this.emitEvent("transitionEnd",[this])}},g.prototype.disableTransition=function(){this.removeTransitionStyles(),this.element.removeEventListener(o,this,!1),this.isTransitioning=!1},g.prototype._removeStyles=function(a){var b={};for(var c in a)b[c]="";this.css(b)};var t={transitionProperty:"",transitionDuration:""};return g.prototype.removeTransitionStyles=function(){this.css(t)},g.prototype.removeElem=function(){this.element.parentNode.removeChild(this.element),this.css({display:""}),this.emitEvent("remove",[this])},g.prototype.remove=function(){if(!k||!parseFloat(this.layout.options.transitionDuration))return void this.removeElem();var a=this;this.once("transitionEnd",function(){a.removeElem()}),this.hide()},g.prototype.reveal=function(){delete this.isHidden,this.css({display:""});var a=this.layout.options,b={},c=this.getHideRevealTransitionEndProperty("visibleStyle");b[c]=this.onRevealTransitionEnd,this.transition({from:a.hiddenStyle,to:a.visibleStyle,isCleaning:!0,onTransitionEnd:b})},g.prototype.onRevealTransitionEnd=function(){this.isHidden||this.emitEvent("reveal")},g.prototype.getHideRevealTransitionEndProperty=function(a){var b=this.layout.options[a];if(b.opacity)return"opacity";for(var c in b)return c},g.prototype.hide=function(){this.isHidden=!0,this.css({display:""});var a=this.layout.options,b={},c=this.getHideRevealTransitionEndProperty("hiddenStyle");b[c]=this.onHideTransitionEnd,this.transition({from:a.visibleStyle,to:a.hiddenStyle,isCleaning:!0,onTransitionEnd:b})},g.prototype.onHideTransitionEnd=function(){this.isHidden&&(this.css({display:"none"}),this.emitEvent("hide"))},g.prototype.destroy=function(){this.css({position:"",left:"",right:"",top:"",bottom:"",transition:"",transform:""})},g}),function(a,b){"function"==typeof define&&define.amd?define("outlayer/outlayer",["eventie/eventie","eventEmitter/EventEmitter","get-size/get-size","fizzy-ui-utils/utils","./item"],function(c,d,e,f,g){return b(a,c,d,e,f,g)}):"object"==typeof exports?module.exports=b(a,require("eventie"),require("wolfy87-eventemitter"),require("get-size"),require("fizzy-ui-utils"),require("./item")):a.Outlayer=b(a,a.eventie,a.EventEmitter,a.getSize,a.fizzyUIUtils,a.Outlayer.Item)}(window,function(a,b,c,d,e,f){function g(a,b){var c=e.getQueryElement(a);if(!c)return void(h&&h.error("Bad element for "+this.constructor.namespace+": "+(c||a)));this.element=c,i&&(this.$element=i(this.element)),this.options=e.extend({},this.constructor.defaults),this.option(b);var d=++k;this.element.outlayerGUID=d,l[d]=this,this._create(),this.options.isInitLayout&&this.layout()}
var h=a.console,i=a.jQuery,j=function(){},k=0,l={};return g.namespace="outlayer",g.Item=f,g.defaults={containerStyle:{position:"relative"},isInitLayout:!0,isOriginLeft:!0,isOriginTop:!0,isResizeBound:!0,isResizingContainer:!0,transitionDuration:"0.4s",hiddenStyle:{opacity:0,transform:"scale(0.001)"},visibleStyle:{opacity:1,transform:"scale(1)"}},e.extend(g.prototype,c.prototype),g.prototype.option=function(a){e.extend(this.options,a)},g.prototype._create=function(){this.reloadItems(),this.stamps=[],this.stamp(this.options.stamp),e.extend(this.element.style,this.options.containerStyle),this.options.isResizeBound&&this.bindResize()},g.prototype.reloadItems=function(){this.items=this._itemize(this.element.children)},g.prototype._itemize=function(a){for(var b=this._filterFindItemElements(a),c=this.constructor.Item,d=[],e=0,f=b.length;f>e;e++){var g=b[e],h=new c(g,this);d.push(h)}
return d},g.prototype._filterFindItemElements=function(a){return e.filterFindElements(a,this.options.itemSelector)},g.prototype.getItemElements=function(){for(var a=[],b=0,c=this.items.length;c>b;b++)a.push(this.items[b].element);return a},g.prototype.layout=function(){this._resetLayout(),this._manageStamps();var a=void 0!==this.options.isLayoutInstant?this.options.isLayoutInstant:!this._isLayoutInited;this.layoutItems(this.items,a),this._isLayoutInited=!0},g.prototype._init=g.prototype.layout,g.prototype._resetLayout=function(){this.getSize()},g.prototype.getSize=function(){this.size=d(this.element)},g.prototype._getMeasurement=function(a,b){var c,f=this.options[a];f?("string"==typeof f?c=this.element.querySelector(f):e.isElement(f)&&(c=f),this[a]=c?d(c)[b]:f):this[a]=0},g.prototype.layoutItems=function(a,b){a=this._getItemsForLayout(a),this._layoutItems(a,b),this._postLayout()},g.prototype._getItemsForLayout=function(a){for(var b=[],c=0,d=a.length;d>c;c++){var e=a[c];e.isIgnored||b.push(e)}
return b},g.prototype._layoutItems=function(a,b){if(this._emitCompleteOnItems("layout",a),a&&a.length){for(var c=[],d=0,e=a.length;e>d;d++){var f=a[d],g=this._getItemLayoutPosition(f);g.item=f,g.isInstant=b||f.isLayoutInstant,c.push(g)}
this._processLayoutQueue(c)}},g.prototype._getItemLayoutPosition=function(){return{x:0,y:0}},g.prototype._processLayoutQueue=function(a){for(var b=0,c=a.length;c>b;b++){var d=a[b];this._positionItem(d.item,d.x,d.y,d.isInstant)}},g.prototype._positionItem=function(a,b,c,d){d?a.goTo(b,c):a.moveTo(b,c)},g.prototype._postLayout=function(){this.resizeContainer()},g.prototype.resizeContainer=function(){if(this.options.isResizingContainer){var a=this._getContainerSize();a&&(this._setContainerMeasure(a.width,!0),this._setContainerMeasure(a.height,!1))}},g.prototype._getContainerSize=j,g.prototype._setContainerMeasure=function(a,b){if(void 0!==a){var c=this.size;c.isBorderBox&&(a+=b?c.paddingLeft+c.paddingRight+c.borderLeftWidth+c.borderRightWidth:c.paddingBottom+c.paddingTop+c.borderTopWidth+c.borderBottomWidth),a=Math.max(a,0),this.element.style[b?"width":"height"]=a+"px"}},g.prototype._emitCompleteOnItems=function(a,b){function c(){e.dispatchEvent(a+"Complete",null,[b])}
function d(){g++,g===f&&c()}
var e=this,f=b.length;if(!b||!f)return void c();for(var g=0,h=0,i=b.length;i>h;h++){var j=b[h];j.once(a,d)}},g.prototype.dispatchEvent=function(a,b,c){var d=b?[b].concat(c):c;if(this.emitEvent(a,d),i)
if(this.$element=this.$element||i(this.element),b){var e=i.Event(b);e.type=a,this.$element.trigger(e,c)}else this.$element.trigger(a,c)},g.prototype.ignore=function(a){var b=this.getItem(a);b&&(b.isIgnored=!0)},g.prototype.unignore=function(a){var b=this.getItem(a);b&&delete b.isIgnored},g.prototype.stamp=function(a){if(a=this._find(a)){this.stamps=this.stamps.concat(a);for(var b=0,c=a.length;c>b;b++){var d=a[b];this.ignore(d)}}},g.prototype.unstamp=function(a){if(a=this._find(a))
for(var b=0,c=a.length;c>b;b++){var d=a[b];e.removeFrom(this.stamps,d),this.unignore(d)}},g.prototype._find=function(a){return a?("string"==typeof a&&(a=this.element.querySelectorAll(a)),a=e.makeArray(a)):void 0},g.prototype._manageStamps=function(){if(this.stamps&&this.stamps.length){this._getBoundingRect();for(var a=0,b=this.stamps.length;b>a;a++){var c=this.stamps[a];this._manageStamp(c)}}},g.prototype._getBoundingRect=function(){var a=this.element.getBoundingClientRect(),b=this.size;this._boundingRect={left:a.left+b.paddingLeft+b.borderLeftWidth,top:a.top+b.paddingTop+b.borderTopWidth,right:a.right-(b.paddingRight+b.borderRightWidth),bottom:a.bottom-(b.paddingBottom+b.borderBottomWidth)}},g.prototype._manageStamp=j,g.prototype._getElementOffset=function(a){var b=a.getBoundingClientRect(),c=this._boundingRect,e=d(a),f={left:b.left-c.left-e.marginLeft,top:b.top-c.top-e.marginTop,right:c.right-b.right-e.marginRight,bottom:c.bottom-b.bottom-e.marginBottom};return f},g.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},g.prototype.bindResize=function(){this.isResizeBound||(b.bind(a,"resize",this),this.isResizeBound=!0)},g.prototype.unbindResize=function(){this.isResizeBound&&b.unbind(a,"resize",this),this.isResizeBound=!1},g.prototype.onresize=function(){function a(){b.resize(),delete b.resizeTimeout}
this.resizeTimeout&&clearTimeout(this.resizeTimeout);var b=this;this.resizeTimeout=setTimeout(a,100)},g.prototype.resize=function(){this.isResizeBound&&this.needsResizeLayout()&&this.layout()},g.prototype.needsResizeLayout=function(){var a=d(this.element),b=this.size&&a;return b&&a.innerWidth!==this.size.innerWidth},g.prototype.addItems=function(a){var b=this._itemize(a);return b.length&&(this.items=this.items.concat(b)),b},g.prototype.appended=function(a){var b=this.addItems(a);b.length&&(this.layoutItems(b,!0),this.reveal(b))},g.prototype.prepended=function(a){var b=this._itemize(a);if(b.length){var c=this.items.slice(0);this.items=b.concat(c),this._resetLayout(),this._manageStamps(),this.layoutItems(b,!0),this.reveal(b),this.layoutItems(c)}},g.prototype.reveal=function(a){this._emitCompleteOnItems("reveal",a);for(var b=a&&a.length,c=0;b&&b>c;c++){var d=a[c];d.reveal()}},g.prototype.hide=function(a){this._emitCompleteOnItems("hide",a);for(var b=a&&a.length,c=0;b&&b>c;c++){var d=a[c];d.hide()}},g.prototype.revealItemElements=function(a){var b=this.getItems(a);this.reveal(b)},g.prototype.hideItemElements=function(a){var b=this.getItems(a);this.hide(b)},g.prototype.getItem=function(a){for(var b=0,c=this.items.length;c>b;b++){var d=this.items[b];if(d.element===a)return d}},g.prototype.getItems=function(a){a=e.makeArray(a);for(var b=[],c=0,d=a.length;d>c;c++){var f=a[c],g=this.getItem(f);g&&b.push(g)}
return b},g.prototype.remove=function(a){var b=this.getItems(a);if(this._emitCompleteOnItems("remove",b),b&&b.length)
for(var c=0,d=b.length;d>c;c++){var f=b[c];f.remove(),e.removeFrom(this.items,f)}},g.prototype.destroy=function(){var a=this.element.style;a.height="",a.position="",a.width="";for(var b=0,c=this.items.length;c>b;b++){var d=this.items[b];d.destroy()}
this.unbindResize();var e=this.element.outlayerGUID;delete l[e],delete this.element.outlayerGUID,i&&i.removeData(this.element,this.constructor.namespace)},g.data=function(a){a=e.getQueryElement(a);var b=a&&a.outlayerGUID;return b&&l[b]},g.create=function(a,b){function c(){g.apply(this,arguments)}
return Object.create?c.prototype=Object.create(g.prototype):e.extend(c.prototype,g.prototype),c.prototype.constructor=c,c.defaults=e.extend({},g.defaults),e.extend(c.defaults,b),c.prototype.settings={},c.namespace=a,c.data=g.data,c.Item=function(){f.apply(this,arguments)},c.Item.prototype=new f,e.htmlInit(c,a),i&&i.bridget&&i.bridget(a,c),c},g.Item=f,g}),function(a,b){"function"==typeof define&&define.amd?define(["outlayer/outlayer","get-size/get-size","fizzy-ui-utils/utils"],b):"object"==typeof exports?module.exports=b(require("outlayer"),require("get-size"),require("fizzy-ui-utils")):a.Masonry=b(a.Outlayer,a.getSize,a.fizzyUIUtils)}(window,function(a,b,c){var d=a.create("masonry");return d.prototype._resetLayout=function(){this.getSize(),this._getMeasurement("columnWidth","outerWidth"),this._getMeasurement("gutter","outerWidth"),this.measureColumns();var a=this.cols;for(this.colYs=[];a--;)this.colYs.push(0);this.maxY=0},d.prototype.measureColumns=function(){if(this.getContainerWidth(),!this.columnWidth){var a=this.items[0],c=a&&a.element;this.columnWidth=c&&b(c).outerWidth||this.containerWidth}
var d=this.columnWidth+=this.gutter,e=this.containerWidth+this.gutter,f=e/d,g=d-e%d,h=g&&1>g?"round":"floor";f=Math[h](f),this.cols=Math.max(f,1)},d.prototype.getContainerWidth=function(){var a=this.options.isFitWidth?this.element.parentNode:this.element,c=b(a);this.containerWidth=c&&c.innerWidth},d.prototype._getItemLayoutPosition=function(a){a.getSize();var b=a.size.outerWidth%this.columnWidth,d=b&&1>b?"round":"ceil",e=Math[d](a.size.outerWidth/this.columnWidth);e=Math.min(e,this.cols);for(var f=this._getColGroup(e),g=Math.min.apply(Math,f),h=c.indexOf(f,g),i={x:this.columnWidth*h,y:g},j=g+a.size.outerHeight,k=this.cols+1-f.length,l=0;k>l;l++)this.colYs[h+l]=j;return i},d.prototype._getColGroup=function(a){if(2>a)return this.colYs;for(var b=[],c=this.cols+1-a,d=0;c>d;d++){var e=this.colYs.slice(d,d+a);b[d]=Math.max.apply(Math,e)}
return b},d.prototype._manageStamp=function(a){var c=b(a),d=this._getElementOffset(a),e=this.options.isOriginLeft?d.left:d.right,f=e+c.outerWidth,g=Math.floor(e/this.columnWidth);g=Math.max(0,g);var h=Math.floor(f/this.columnWidth);h-=f%this.columnWidth?0:1,h=Math.min(this.cols-1,h);for(var i=(this.options.isOriginTop?d.top:d.bottom)+c.outerHeight,j=g;h>=j;j++)this.colYs[j]=Math.max(i,this.colYs[j])},d.prototype._getContainerSize=function(){this.maxY=Math.max.apply(Math,this.colYs);var a={height:this.maxY};return this.options.isFitWidth&&(a.width=this._getContainerFitWidth()),a},d.prototype._getContainerFitWidth=function(){for(var a=0,b=this.cols;--b&&0===this.colYs[b];)a++;return(this.cols-a)*this.columnWidth-this.gutter},d.prototype.needsResizeLayout=function(){var a=this.containerWidth;return this.getContainerWidth(),a!==this.containerWidth},d});jQuery.onFontResize=(function($){$(function(){var randomID='font-resize-frame-'+Math.floor(Math.random()*1000);var resizeFrame=$('<iframe>').attr('id',randomID).addClass('font-resize-helper');resizeFrame.css({width:'100em',height:'10px',position:'absolute',borderWidth:0,top:'-9999px',left:'-9999px'}).appendTo('body');if(window.attachEvent&&!window.addEventListener){resizeFrame.bind('resize',function(){$.onFontResize.trigger(resizeFrame[0].offsetWidth/100);});}
else{var doc=resizeFrame[0].contentWindow.document;doc.open();doc.write('<scri'+'pt>window.onload = function(){var em = parent.jQuery("#'+randomID+'")[0];window.onresize = function(){if(parent.jQuery.onFontResize){parent.jQuery.onFontResize.trigger(em.offsetWidth / 100);}}};</scri'+'pt>');doc.close();}
jQuery.onFontResize.initialSize=resizeFrame[0].offsetWidth/100;});return{trigger:function(em){$(window).trigger("fontresize",[em]);}};}(jQuery));;(function(root,factory){'use strict';if(typeof define==='function'&&define.amd){define(['jquery'],factory);}else if(typeof exports==='object'){module.exports=factory(require('jquery'));}else{root.jcf=factory(jQuery);}}(this,function($){'use strict';var version='1.1.3';var customInstances=[];var commonOptions={optionsKey:'jcf',dataKey:'jcf-instance',rtlClass:'jcf-rtl',focusClass:'jcf-focus',pressedClass:'jcf-pressed',disabledClass:'jcf-disabled',hiddenClass:'jcf-hidden',resetAppearanceClass:'jcf-reset-appearance',unselectableClass:'jcf-unselectable'};var isTouchDevice=('ontouchstart'in window)||window.DocumentTouch&&document instanceof window.DocumentTouch,isWinPhoneDevice=/Windows Phone/.test(navigator.userAgent);commonOptions.isMobileDevice=!!(isTouchDevice||isWinPhoneDevice);var createStyleSheet=function(){var styleTag=$('<style>').appendTo('head'),styleSheet=styleTag.prop('sheet')||styleTag.prop('styleSheet');var addCSSRule=function(selector,rules,index){if(styleSheet.insertRule){styleSheet.insertRule(selector+'{'+rules+'}',index);}else{styleSheet.addRule(selector,rules,index);}};addCSSRule('.'+commonOptions.hiddenClass,'position:absolute !important;left:-9999px !important;height:1px !important;width:1px !important;margin:0 !important;border-width:0 !important;-webkit-appearance:none;-moz-appearance:none;appearance:none');addCSSRule('.'+commonOptions.rtlClass+' .'+commonOptions.hiddenClass,'right:-9999px !important; left: auto !important');addCSSRule('.'+commonOptions.unselectableClass,'-webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; -webkit-tap-highlight-color: rgba(0,0,0,0);');addCSSRule('.'+commonOptions.resetAppearanceClass,'background: none; border: none; -webkit-appearance: none; appearance: none; opacity: 0; filter: alpha(opacity=0);');var html=$('html'),body=$('body');if(html.css('direction')==='rtl'||body.css('direction')==='rtl'){html.addClass(commonOptions.rtlClass);}
html.on('reset',function(){setTimeout(function(){api.refreshAll();},0);});commonOptions.styleSheetCreated=true;};(function(){var pointerEventsSupported=navigator.pointerEnabled||navigator.msPointerEnabled,touchEventsSupported=('ontouchstart'in window)||window.DocumentTouch&&document instanceof window.DocumentTouch,eventList,eventMap={},eventPrefix='jcf-';if(pointerEventsSupported){eventList={pointerover:navigator.pointerEnabled?'pointerover':'MSPointerOver',pointerdown:navigator.pointerEnabled?'pointerdown':'MSPointerDown',pointermove:navigator.pointerEnabled?'pointermove':'MSPointerMove',pointerup:navigator.pointerEnabled?'pointerup':'MSPointerUp'};}else{eventList={pointerover:'mouseover',pointerdown:'mousedown'+(touchEventsSupported?' touchstart':''),pointermove:'mousemove'+(touchEventsSupported?' touchmove':''),pointerup:'mouseup'+(touchEventsSupported?' touchend':'')};}
$.each(eventList,function(targetEventName,fakeEventList){$.each(fakeEventList.split(' '),function(index,fakeEventName){eventMap[fakeEventName]=targetEventName;});});$.each(eventList,function(eventName,eventHandlers){eventHandlers=eventHandlers.split(' ');$.event.special[eventPrefix+eventName]={setup:function(){var self=this;$.each(eventHandlers,function(index,fallbackEvent){if(self.addEventListener)self.addEventListener(fallbackEvent,fixEvent,false);else self['on'+fallbackEvent]=fixEvent;});},teardown:function(){var self=this;$.each(eventHandlers,function(index,fallbackEvent){if(self.addEventListener)self.removeEventListener(fallbackEvent,fixEvent,false);else self['on'+fallbackEvent]=null;});}};});var lastTouch=null;var mouseEventSimulated=function(e){var dx=Math.abs(e.pageX-lastTouch.x),dy=Math.abs(e.pageY-lastTouch.y),rangeDistance=25;if(dx<=rangeDistance&&dy<=rangeDistance){return true;}};var fixEvent=function(e){var origEvent=e||window.event,touchEventData=null,targetEventName=eventMap[origEvent.type];e=$.event.fix(origEvent);e.type=eventPrefix+targetEventName;if(origEvent.pointerType){switch(origEvent.pointerType){case 2:e.pointerType='touch';break;case 3:e.pointerType='pen';break;case 4:e.pointerType='mouse';break;default:e.pointerType=origEvent.pointerType;}}else{e.pointerType=origEvent.type.substr(0,5);}
if(!e.pageX&&!e.pageY){touchEventData=origEvent.changedTouches?origEvent.changedTouches[0]:origEvent;e.pageX=touchEventData.pageX;e.pageY=touchEventData.pageY;}
if(origEvent.type==='touchend'){lastTouch={x:e.pageX,y:e.pageY};}
if(e.pointerType==='mouse'&&lastTouch&&mouseEventSimulated(e)){return;}else{return($.event.dispatch||$.event.handle).call(this,e);}};}());(function(){var wheelEvents=('onwheel'in document||document.documentMode>=9?'wheel':'mousewheel DOMMouseScroll').split(' '),shimEventName='jcf-mousewheel';$.event.special[shimEventName]={setup:function(){var self=this;$.each(wheelEvents,function(index,fallbackEvent){if(self.addEventListener)self.addEventListener(fallbackEvent,fixEvent,false);else self['on'+fallbackEvent]=fixEvent;});},teardown:function(){var self=this;$.each(wheelEvents,function(index,fallbackEvent){if(self.addEventListener)self.removeEventListener(fallbackEvent,fixEvent,false);else self['on'+fallbackEvent]=null;});}};var fixEvent=function(e){var origEvent=e||window.event;e=$.event.fix(origEvent);e.type=shimEventName;if('detail'in origEvent){e.deltaY=-origEvent.detail;}
if('wheelDelta'in origEvent){e.deltaY=-origEvent.wheelDelta;}
if('wheelDeltaY'in origEvent){e.deltaY=-origEvent.wheelDeltaY;}
if('wheelDeltaX'in origEvent){e.deltaX=-origEvent.wheelDeltaX;}
if('deltaY'in origEvent){e.deltaY=origEvent.deltaY;}
if('deltaX'in origEvent){e.deltaX=origEvent.deltaX;}
e.delta=e.deltaY||e.deltaX;if(origEvent.deltaMode===1){var lineHeight=16;e.delta*=lineHeight;e.deltaY*=lineHeight;e.deltaX*=lineHeight;}
return($.event.dispatch||$.event.handle).call(this,e);};}());var moduleMixin={fireNativeEvent:function(elements,eventName){$(elements).each(function(){var element=this,eventObject;if(element.dispatchEvent){eventObject=document.createEvent('HTMLEvents');eventObject.initEvent(eventName,true,true);element.dispatchEvent(eventObject);}else if(document.createEventObject){eventObject=document.createEventObject();eventObject.target=element;element.fireEvent('on'+eventName,eventObject);}});},bindHandlers:function(){var self=this;$.each(self,function(propName,propValue){if(propName.indexOf('on')===0&&$.isFunction(propValue)){self[propName]=function(){return propValue.apply(self,arguments);};}});}};var api={version:version,modules:{},getOptions:function(){return $.extend({},commonOptions);},setOptions:function(moduleName,moduleOptions){if(arguments.length>1){if(this.modules[moduleName]){$.extend(this.modules[moduleName].prototype.options,moduleOptions);}}else{$.extend(commonOptions,moduleName);}},addModule:function(proto){var Module=function(options){if(!options.element.data(commonOptions.dataKey)){options.element.data(commonOptions.dataKey,this);}
customInstances.push(this);this.options=$.extend({},commonOptions,this.options,getInlineOptions(options.element),options);this.bindHandlers();this.init.apply(this,arguments);};var getInlineOptions=function(element){var dataOptions=element.data(commonOptions.optionsKey),attrOptions=element.attr(commonOptions.optionsKey);if(dataOptions){return dataOptions;}else if(attrOptions){try{return $.parseJSON(attrOptions);}catch(e){}}};Module.prototype=proto;$.extend(proto,moduleMixin);if(proto.plugins){$.each(proto.plugins,function(pluginName,plugin){$.extend(plugin.prototype,moduleMixin);});}
var originalDestroy=Module.prototype.destroy;Module.prototype.destroy=function(){this.options.element.removeData(this.options.dataKey);for(var i=customInstances.length-1;i>=0;i--){if(customInstances[i]===this){customInstances.splice(i,1);break;}}
if(originalDestroy){originalDestroy.apply(this,arguments);}};this.modules[proto.name]=Module;},getInstance:function(element){return $(element).data(commonOptions.dataKey);},replace:function(elements,moduleName,customOptions){var self=this,instance;if(!commonOptions.styleSheetCreated){createStyleSheet();}
$(elements).each(function(){var moduleOptions,element=$(this);instance=element.data(commonOptions.dataKey);if(instance){instance.refresh();}else{if(!moduleName){$.each(self.modules,function(currentModuleName,module){if(module.prototype.matchElement.call(module.prototype,element)){moduleName=currentModuleName;return false;}});}
if(moduleName){moduleOptions=$.extend({element:element},customOptions);instance=new self.modules[moduleName](moduleOptions);}}});return instance;},refresh:function(elements){$(elements).each(function(){var instance=$(this).data(commonOptions.dataKey);if(instance){instance.refresh();}});},destroy:function(elements){$(elements).each(function(){var instance=$(this).data(commonOptions.dataKey);if(instance){instance.destroy();}});},replaceAll:function(context){var self=this;$.each(this.modules,function(moduleName,module){$(module.prototype.selector,context).each(function(){if(this.className.indexOf('jcf-ignore')<0){self.replace(this,moduleName);}});});},refreshAll:function(context){if(context){$.each(this.modules,function(moduleName,module){$(module.prototype.selector,context).each(function(){var instance=$(this).data(commonOptions.dataKey);if(instance){instance.refresh();}});});}else{for(var i=customInstances.length-1;i>=0;i--){customInstances[i].refresh();}}},destroyAll:function(context){if(context){$.each(this.modules,function(moduleName,module){$(module.prototype.selector,context).each(function(index,element){var instance=$(element).data(commonOptions.dataKey);if(instance){instance.destroy();}});});}else{while(customInstances.length){customInstances[0].destroy();}}}};window.jcf=api;return api;}));;(function($,window){'use strict';jcf.addModule({name:'Select',selector:'select',options:{element:null,multipleCompactStyle:false},plugins:{ListBox:ListBox,ComboBox:ComboBox,SelectList:SelectList},matchElement:function(element){return element.is('select');},init:function(){this.element=$(this.options.element);this.createInstance();},isListBox:function(){return this.element.is('[size]:not([jcf-size]), [multiple]');},createInstance:function(){if(this.instance){this.instance.destroy();}
if(this.isListBox()&&!this.options.multipleCompactStyle){this.instance=new ListBox(this.options);}else{this.instance=new ComboBox(this.options);}},refresh:function(){var typeMismatch=(this.isListBox()&&this.instance instanceof ComboBox)||(!this.isListBox()&&this.instance instanceof ListBox);if(typeMismatch){this.createInstance();}else{this.instance.refresh();}},destroy:function(){this.instance.destroy();}});function ComboBox(options){this.options=$.extend({wrapNative:true,wrapNativeOnMobile:true,fakeDropInBody:true,useCustomScroll:true,flipDropToFit:true,maxVisibleItems:10,fakeAreaStructure:'<span class="jcf-select"><span class="jcf-select-text"></span><span class="jcf-select-opener"></span></span>',fakeDropStructure:'<div class="jcf-select-drop"><div class="jcf-select-drop-content"></div></div>',optionClassPrefix:'jcf-option-',selectClassPrefix:'jcf-select-',dropContentSelector:'.jcf-select-drop-content',selectTextSelector:'.jcf-select-text',dropActiveClass:'jcf-drop-active',flipDropClass:'jcf-drop-flipped'},options);this.init();}
$.extend(ComboBox.prototype,{init:function(){this.initStructure();this.bindHandlers();this.attachEvents();this.refresh();},initStructure:function(){this.win=$(window);this.doc=$(document);this.realElement=$(this.options.element);this.fakeElement=$(this.options.fakeAreaStructure).insertAfter(this.realElement);this.selectTextContainer=this.fakeElement.find(this.options.selectTextSelector);this.selectText=$('<span></span>').appendTo(this.selectTextContainer);makeUnselectable(this.fakeElement);this.fakeElement.addClass(getPrefixedClasses(this.realElement.prop('className'),this.options.selectClassPrefix));if(this.realElement.prop('multiple')){this.fakeElement.addClass('jcf-compact-multiple');}
if(this.options.isMobileDevice&&this.options.wrapNativeOnMobile&&!this.options.wrapNative){this.options.wrapNative=true;}
if(this.options.wrapNative){this.realElement.prependTo(this.fakeElement).css({position:'absolute',height:'100%',width:'100%'}).addClass(this.options.resetAppearanceClass);}else{this.realElement.addClass(this.options.hiddenClass);this.fakeElement.attr('title',this.realElement.attr('title'));this.fakeDropTarget=this.options.fakeDropInBody?$('body'):this.fakeElement;}},attachEvents:function(){var self=this;this.delayedRefresh=function(){setTimeout(function(){self.refresh();if(self.list){self.list.refresh();self.list.scrollToActiveOption();}},1);};if(this.options.wrapNative){this.realElement.on({focus:this.onFocus,change:this.onChange,click:this.onChange,keydown:this.onChange});}else{this.realElement.on({focus:this.onFocus,change:this.onChange,keydown:this.onKeyDown});this.fakeElement.on({'jcf-pointerdown':this.onSelectAreaPress});}},onKeyDown:function(e){if(e.which===13){this.toggleDropdown();}else if(this.dropActive){this.delayedRefresh();}},onChange:function(){this.refresh();},onFocus:function(){if(!this.pressedFlag||!this.focusedFlag){this.fakeElement.addClass(this.options.focusClass);this.realElement.on('blur',this.onBlur);this.toggleListMode(true);this.focusedFlag=true;}},onBlur:function(){if(!this.pressedFlag){this.fakeElement.removeClass(this.options.focusClass);this.realElement.off('blur',this.onBlur);this.toggleListMode(false);this.focusedFlag=false;}},onResize:function(){if(this.dropActive){this.hideDropdown();}},onSelectDropPress:function(){this.pressedFlag=true;},onSelectDropRelease:function(e,pointerEvent){this.pressedFlag=false;if(pointerEvent.pointerType==='mouse'){this.realElement.focus();}},onSelectAreaPress:function(e){var dropClickedInsideFakeElement=!this.options.fakeDropInBody&&$(e.target).closest(this.dropdown).length;if(dropClickedInsideFakeElement||e.button>1||this.realElement.is(':disabled')){return;}
this.selectOpenedByEvent=e.pointerType;this.toggleDropdown();if(!this.focusedFlag){if(e.pointerType==='mouse'){this.realElement.focus();}else{this.onFocus(e);}}
this.pressedFlag=true;this.fakeElement.addClass(this.options.pressedClass);this.doc.on('jcf-pointerup',this.onSelectAreaRelease);},onSelectAreaRelease:function(e){if(this.focusedFlag&&e.pointerType==='mouse'){this.realElement.focus();}
this.pressedFlag=false;this.fakeElement.removeClass(this.options.pressedClass);this.doc.off('jcf-pointerup',this.onSelectAreaRelease);},onOutsideClick:function(e){var target=$(e.target),clickedInsideSelect=target.closest(this.fakeElement).length||target.closest(this.dropdown).length;if(!clickedInsideSelect){this.hideDropdown();}},onSelect:function(){this.refresh();if(this.realElement.prop('multiple')){this.repositionDropdown();}else{this.hideDropdown();}
this.fireNativeEvent(this.realElement,'change');},toggleListMode:function(state){if(!this.options.wrapNative){if(state){this.realElement.attr({size:4,'jcf-size':''});}else{if(!this.options.wrapNative){this.realElement.removeAttr('size jcf-size');}}}},createDropdown:function(){if(this.dropdown){this.list.destroy();this.dropdown.remove();}
this.dropdown=$(this.options.fakeDropStructure).appendTo(this.fakeDropTarget);this.dropdown.addClass(getPrefixedClasses(this.realElement.prop('className'),this.options.selectClassPrefix));makeUnselectable(this.dropdown);if(this.realElement.prop('multiple')){this.dropdown.addClass('jcf-compact-multiple');}
if(this.options.fakeDropInBody){this.dropdown.css({position:'absolute',top:-9999});}
this.list=new SelectList({useHoverClass:true,handleResize:false,alwaysPreventMouseWheel:true,maxVisibleItems:this.options.maxVisibleItems,useCustomScroll:this.options.useCustomScroll,holder:this.dropdown.find(this.options.dropContentSelector),multipleSelectWithoutKey:this.realElement.prop('multiple'),element:this.realElement});$(this.list).on({select:this.onSelect,press:this.onSelectDropPress,release:this.onSelectDropRelease});},repositionDropdown:function(){var selectOffset=this.fakeElement.offset(),selectWidth=this.fakeElement.outerWidth(),selectHeight=this.fakeElement.outerHeight(),dropHeight=this.dropdown.css('width',selectWidth).outerHeight(),winScrollTop=this.win.scrollTop(),winHeight=this.win.height(),calcTop,calcLeft,bodyOffset,needFlipDrop=false;if(selectOffset.top+selectHeight+dropHeight>winScrollTop+winHeight&&selectOffset.top-dropHeight>winScrollTop){needFlipDrop=true;}
if(this.options.fakeDropInBody){bodyOffset=this.fakeDropTarget.css('position')!=='static'?this.fakeDropTarget.offset().top:0;if(this.options.flipDropToFit&&needFlipDrop){calcLeft=selectOffset.left;calcTop=selectOffset.top-dropHeight-bodyOffset;}else{calcLeft=selectOffset.left;calcTop=selectOffset.top+selectHeight-bodyOffset;}
this.dropdown.css({width:selectWidth,left:calcLeft,top:calcTop});}
this.dropdown.add(this.fakeElement).toggleClass(this.options.flipDropClass,this.options.flipDropToFit&&needFlipDrop);},showDropdown:function(){if(!this.realElement.prop('options').length){return;}
if(!this.dropdown){this.createDropdown();}
this.dropActive=true;this.dropdown.appendTo(this.fakeDropTarget);this.fakeElement.addClass(this.options.dropActiveClass);this.refreshSelectedText();this.repositionDropdown();this.list.setScrollTop(this.savedScrollTop);this.list.refresh();this.win.on('resize',this.onResize);this.doc.on('jcf-pointerdown',this.onOutsideClick);},hideDropdown:function(){if(this.dropdown){this.savedScrollTop=this.list.getScrollTop();this.fakeElement.removeClass(this.options.dropActiveClass+' '+this.options.flipDropClass);this.dropdown.removeClass(this.options.flipDropClass).detach();this.doc.off('jcf-pointerdown',this.onOutsideClick);this.win.off('resize',this.onResize);this.dropActive=false;if(this.selectOpenedByEvent==='touch'){this.onBlur();}}},toggleDropdown:function(){if(this.dropActive){this.hideDropdown();}else{this.showDropdown();}},refreshSelectedText:function(){var selectedIndex=this.realElement.prop('selectedIndex'),selectedOption=this.realElement.prop('options')[selectedIndex],selectedOptionImage=selectedOption?selectedOption.getAttribute('data-image'):null,selectedOptionText='',selectedOptionClasses,self=this;if(this.realElement.prop('multiple')){$.each(this.realElement.prop('options'),function(index,option){if(option.selected){selectedOptionText+=(selectedOptionText?', ':'')+option.innerHTML;}});if(!selectedOptionText){selectedOptionText=self.realElement.attr('placeholder')||'';}
this.selectText.removeAttr('class').html(selectedOptionText);}else if(!selectedOption){if(this.selectImage){this.selectImage.hide();}
this.selectText.removeAttr('class').empty();}else if(this.currentSelectedText!==selectedOption.innerHTML||this.currentSelectedImage!==selectedOptionImage){selectedOptionClasses=getPrefixedClasses(selectedOption.className,this.options.optionClassPrefix);this.selectText.attr('class',selectedOptionClasses).html(selectedOption.innerHTML);if(selectedOptionImage){if(!this.selectImage){this.selectImage=$('<img>').prependTo(this.selectTextContainer).hide();}
this.selectImage.attr('src',selectedOptionImage).show();}else if(this.selectImage){this.selectImage.hide();}
this.currentSelectedText=selectedOption.innerHTML;this.currentSelectedImage=selectedOptionImage;}},refresh:function(){if(this.realElement.prop('style').display==='none'){this.fakeElement.hide();}else{this.fakeElement.show();}
this.refreshSelectedText();this.fakeElement.toggleClass(this.options.disabledClass,this.realElement.is(':disabled'));},destroy:function(){if(this.options.wrapNative){this.realElement.insertBefore(this.fakeElement).css({position:'',height:'',width:''}).removeClass(this.options.resetAppearanceClass);}else{this.realElement.removeClass(this.options.hiddenClass);if(this.realElement.is('[jcf-size]')){this.realElement.removeAttr('size jcf-size');}}
this.fakeElement.remove();this.doc.off('jcf-pointerup',this.onSelectAreaRelease);this.realElement.off({focus:this.onFocus});}});function ListBox(options){this.options=$.extend({wrapNative:true,useCustomScroll:true,fakeStructure:'<span class="jcf-list-box"><span class="jcf-list-wrapper"></span></span>',selectClassPrefix:'jcf-select-',listHolder:'.jcf-list-wrapper'},options);this.init();}
$.extend(ListBox.prototype,{init:function(){this.bindHandlers();this.initStructure();this.attachEvents();},initStructure:function(){this.realElement=$(this.options.element);this.fakeElement=$(this.options.fakeStructure).insertAfter(this.realElement);this.listHolder=this.fakeElement.find(this.options.listHolder);makeUnselectable(this.fakeElement);this.fakeElement.addClass(getPrefixedClasses(this.realElement.prop('className'),this.options.selectClassPrefix));this.realElement.addClass(this.options.hiddenClass);this.list=new SelectList({useCustomScroll:this.options.useCustomScroll,holder:this.listHolder,selectOnClick:false,element:this.realElement});},attachEvents:function(){var self=this;this.delayedRefresh=function(e){if(e&&e.which===16){return;}else{clearTimeout(self.refreshTimer);self.refreshTimer=setTimeout(function(){self.refresh();self.list.scrollToActiveOption();},1);}};this.realElement.on({focus:this.onFocus,click:this.delayedRefresh,keydown:this.delayedRefresh});$(this.list).on({select:this.onSelect,press:this.onFakeOptionsPress,release:this.onFakeOptionsRelease});},onFakeOptionsPress:function(e,pointerEvent){this.pressedFlag=true;if(pointerEvent.pointerType==='mouse'){this.realElement.focus();}},onFakeOptionsRelease:function(e,pointerEvent){this.pressedFlag=false;if(pointerEvent.pointerType==='mouse'){this.realElement.focus();}},onSelect:function(){this.fireNativeEvent(this.realElement,'change');this.fireNativeEvent(this.realElement,'click');},onFocus:function(){if(!this.pressedFlag||!this.focusedFlag){this.fakeElement.addClass(this.options.focusClass);this.realElement.on('blur',this.onBlur);this.focusedFlag=true;}},onBlur:function(){if(!this.pressedFlag){this.fakeElement.removeClass(this.options.focusClass);this.realElement.off('blur',this.onBlur);this.focusedFlag=false;}},refresh:function(){this.fakeElement.toggleClass(this.options.disabledClass,this.realElement.is(':disabled'));this.list.refresh();},destroy:function(){this.list.destroy();this.realElement.insertBefore(this.fakeElement).removeClass(this.options.hiddenClass);this.fakeElement.remove();}});function SelectList(options){this.options=$.extend({holder:null,maxVisibleItems:10,selectOnClick:true,useHoverClass:false,useCustomScroll:false,handleResize:true,multipleSelectWithoutKey:false,alwaysPreventMouseWheel:false,indexAttribute:'data-index',cloneClassPrefix:'jcf-option-',containerStructure:'<span class="jcf-list"><span class="jcf-list-content"></span></span>',containerSelector:'.jcf-list-content',captionClass:'jcf-optgroup-caption',disabledClass:'jcf-disabled',optionClass:'jcf-option',groupClass:'jcf-optgroup',hoverClass:'jcf-hover',selectedClass:'jcf-selected',scrollClass:'jcf-scroll-active'},options);this.init();}
$.extend(SelectList.prototype,{init:function(){this.initStructure();this.refreshSelectedClass();this.attachEvents();},initStructure:function(){this.element=$(this.options.element);this.indexSelector='['+this.options.indexAttribute+']';this.container=$(this.options.containerStructure).appendTo(this.options.holder);this.listHolder=this.container.find(this.options.containerSelector);this.lastClickedIndex=this.element.prop('selectedIndex');this.rebuildList();},attachEvents:function(){this.bindHandlers();this.listHolder.on('jcf-pointerdown',this.indexSelector,this.onItemPress);this.listHolder.on('jcf-pointerdown',this.onPress);if(this.options.useHoverClass){this.listHolder.on('jcf-pointerover',this.indexSelector,this.onHoverItem);}},onPress:function(e){$(this).trigger('press',e);this.listHolder.on('jcf-pointerup',this.onRelease);},onRelease:function(e){$(this).trigger('release',e);this.listHolder.off('jcf-pointerup',this.onRelease);},onHoverItem:function(e){var hoverIndex=parseFloat(e.currentTarget.getAttribute(this.options.indexAttribute));this.fakeOptions.removeClass(this.options.hoverClass).eq(hoverIndex).addClass(this.options.hoverClass);},onItemPress:function(e){if(e.pointerType==='touch'||this.options.selectOnClick){this.tmpListOffsetTop=this.list.offset().top;this.listHolder.on('jcf-pointerup',this.indexSelector,this.onItemRelease);}else{this.onSelectItem(e);}},onItemRelease:function(e){this.listHolder.off('jcf-pointerup',this.indexSelector,this.onItemRelease);if(this.tmpListOffsetTop===this.list.offset().top){this.listHolder.on('click',this.indexSelector,{savedPointerType:e.pointerType},this.onSelectItem);}
delete this.tmpListOffsetTop;},onSelectItem:function(e){var clickedIndex=parseFloat(e.currentTarget.getAttribute(this.options.indexAttribute)),pointerType=e.data&&e.data.savedPointerType||e.pointerType||'mouse',range;this.listHolder.off('click',this.indexSelector,this.onSelectItem);if(e.button>1||this.realOptions[clickedIndex].disabled){return;}
if(this.element.prop('multiple')){if(e.metaKey||e.ctrlKey||pointerType==='touch'||this.options.multipleSelectWithoutKey){this.realOptions[clickedIndex].selected=!this.realOptions[clickedIndex].selected;}else if(e.shiftKey){range=[this.lastClickedIndex,clickedIndex].sort(function(a,b){return a-b;});this.realOptions.each(function(index,option){option.selected=(index>=range[0]&&index<=range[1]);});}else{this.element.prop('selectedIndex',clickedIndex);}}else{this.element.prop('selectedIndex',clickedIndex);}
if(!e.shiftKey){this.lastClickedIndex=clickedIndex;}
this.refreshSelectedClass();if(pointerType==='mouse'){this.scrollToActiveOption();}
$(this).trigger('select');},rebuildList:function(){var self=this,rootElement=this.element[0];this.storedSelectHTML=rootElement.innerHTML;this.optionIndex=0;this.list=$(this.createOptionsList(rootElement));this.listHolder.empty().append(this.list);this.realOptions=this.element.find('option');this.fakeOptions=this.list.find(this.indexSelector);this.fakeListItems=this.list.find('.'+this.options.captionClass+','+this.indexSelector);delete this.optionIndex;var maxCount=this.options.maxVisibleItems,sizeValue=this.element.prop('size');if(sizeValue>1&&!this.element.is('[jcf-size]')){maxCount=sizeValue;}
var needScrollBar=this.fakeOptions.length>maxCount;this.container.toggleClass(this.options.scrollClass,needScrollBar);if(needScrollBar){this.listHolder.css({maxHeight:this.getOverflowHeight(maxCount),overflow:'auto'});if(this.options.useCustomScroll&&jcf.modules.Scrollable){jcf.replace(this.listHolder,'Scrollable',{handleResize:this.options.handleResize,alwaysPreventMouseWheel:this.options.alwaysPreventMouseWheel});return;}}
if(this.options.alwaysPreventMouseWheel){this.preventWheelHandler=function(e){var currentScrollTop=self.listHolder.scrollTop(),maxScrollTop=self.listHolder.prop('scrollHeight')-self.listHolder.innerHeight();if((currentScrollTop<=0&&e.deltaY<0)||(currentScrollTop>=maxScrollTop&&e.deltaY>0)){e.preventDefault();}};this.listHolder.on('jcf-mousewheel',this.preventWheelHandler);}},refreshSelectedClass:function(){var self=this,selectedItem,isMultiple=this.element.prop('multiple'),selectedIndex=this.element.prop('selectedIndex');if(isMultiple){this.realOptions.each(function(index,option){self.fakeOptions.eq(index).toggleClass(self.options.selectedClass,!!option.selected);});}else{this.fakeOptions.removeClass(this.options.selectedClass+' '+this.options.hoverClass);selectedItem=this.fakeOptions.eq(selectedIndex).addClass(this.options.selectedClass);if(this.options.useHoverClass){selectedItem.addClass(this.options.hoverClass);}}},scrollToActiveOption:function(){var targetOffset=this.getActiveOptionOffset();if(typeof targetOffset==='number'){this.listHolder.prop('scrollTop',targetOffset);}},getSelectedIndexRange:function(){var firstSelected=-1,lastSelected=-1;this.realOptions.each(function(index,option){if(option.selected){if(firstSelected<0){firstSelected=index;}
lastSelected=index;}});return[firstSelected,lastSelected];},getChangedSelectedIndex:function(){var selectedIndex=this.element.prop('selectedIndex'),targetIndex;if(this.element.prop('multiple')){if(!this.previousRange){this.previousRange=[selectedIndex,selectedIndex];}
this.currentRange=this.getSelectedIndexRange();targetIndex=this.currentRange[this.currentRange[0]!==this.previousRange[0]?0:1];this.previousRange=this.currentRange;return targetIndex;}else{return selectedIndex;}},getActiveOptionOffset:function(){var dropHeight=this.listHolder.height(),dropScrollTop=this.listHolder.prop('scrollTop'),currentIndex=this.getChangedSelectedIndex(),fakeOption=this.fakeOptions.eq(currentIndex),fakeOptionOffset=fakeOption.offset().top-this.list.offset().top,fakeOptionHeight=fakeOption.innerHeight();if(fakeOptionOffset+fakeOptionHeight>=dropScrollTop+dropHeight){return fakeOptionOffset-dropHeight+fakeOptionHeight;}else if(fakeOptionOffset<dropScrollTop){return fakeOptionOffset;}},getOverflowHeight:function(sizeValue){var item=this.fakeListItems.eq(sizeValue-1),listOffset=this.list.offset().top,itemOffset=item.offset().top,itemHeight=item.innerHeight();return itemOffset+itemHeight-listOffset;},getScrollTop:function(){return this.listHolder.scrollTop();},setScrollTop:function(value){this.listHolder.scrollTop(value);},createOption:function(option){var newOption=document.createElement('span');newOption.className=this.options.optionClass;newOption.innerHTML=option.innerHTML;newOption.setAttribute(this.options.indexAttribute,this.optionIndex++);var optionImage,optionImageSrc=option.getAttribute('data-image');if(optionImageSrc){optionImage=document.createElement('img');optionImage.src=optionImageSrc;newOption.insertBefore(optionImage,newOption.childNodes[0]);}
if(option.disabled){newOption.className+=' '+this.options.disabledClass;}
if(option.className){newOption.className+=' '+getPrefixedClasses(option.className,this.options.cloneClassPrefix);}
return newOption;},createOptGroup:function(optgroup){var optGroupContainer=document.createElement('span'),optGroupName=optgroup.getAttribute('label'),optGroupCaption,optGroupList;optGroupCaption=document.createElement('span');optGroupCaption.className=this.options.captionClass;optGroupCaption.innerHTML=optGroupName;optGroupContainer.appendChild(optGroupCaption);if(optgroup.children.length){optGroupList=this.createOptionsList(optgroup);optGroupContainer.appendChild(optGroupList);}
optGroupContainer.className=this.options.groupClass;return optGroupContainer;},createOptionContainer:function(){var optionContainer=document.createElement('li');return optionContainer;},createOptionsList:function(container){var self=this,list=document.createElement('ul');$.each(container.children,function(index,currentNode){var item=self.createOptionContainer(currentNode),newNode;switch(currentNode.tagName.toLowerCase()){case'option':newNode=self.createOption(currentNode);break;case'optgroup':newNode=self.createOptGroup(currentNode);break;}
list.appendChild(item).appendChild(newNode);});return list;},refresh:function(){if(this.storedSelectHTML!==this.element.prop('innerHTML')){this.rebuildList();}
var scrollInstance=jcf.getInstance(this.listHolder);if(scrollInstance){scrollInstance.refresh();}
this.refreshSelectedClass();},destroy:function(){this.listHolder.off('jcf-mousewheel',this.preventWheelHandler);this.listHolder.off('jcf-pointerdown',this.indexSelector,this.onSelectItem);this.listHolder.off('jcf-pointerover',this.indexSelector,this.onHoverItem);this.listHolder.off('jcf-pointerdown',this.onPress);}});var getPrefixedClasses=function(className,prefixToAdd){return className?className.replace(/[\s]*([\S]+)+[\s]*/gi,prefixToAdd+'$1 '):'';};var makeUnselectable=(function(){var unselectableClass=jcf.getOptions().unselectableClass;function preventHandler(e){e.preventDefault();}
return function(node){node.addClass(unselectableClass).on('selectstart',preventHandler);};}());}(jQuery,this));